print("     /~\\") # 단순 출력 구현
print("    ( oo|")
print("    _\\=/_")
print("   /  _  \\")
print("  //|/.\\|\\\\")
print(" ||  \\ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")